GAME_NAME = "Bomberboy"
FONT_SIZE = 70

#Display constants
WINDOW_WIDTH = 480
WINDOW_HEIGHT = 352
SQUARE_SIZE = 32

#Map unit constants
UNIT_EMPTY = 0
UNIT_PLAYER = 1
UNIT_FIXED_BLOCK =2
UNIT_BLOCK = 3
UNIT_POWERUP_FIRE = 4
UNIT_POWERUP_VELOCITY = 5
UNIT_POWERUP_BOMB = 6
UNIT_BOMB = 7
UNIT_FIRE = 8

