GAME_NAME = "bomberboy"
FONT_SIZE = 40
MAX_FPS = 200

# Display constants
WINDOW_WIDTH = 480
WINDOW_HEIGHT = 352
SQUARE_SIZE = 32

# Map unit constants
UNIT_EMPTY = 0
UNIT_PLAYER = 1
UNIT_FIXED_BLOCK = 2
UNIT_BLOCK = 3
UNIT_POWERUP_FIRE = 4
UNIT_POWERUP_VELOCITY = 5
UNIT_POWERUP_BOMB = 6
UNIT_BOMB = 7
UNIT_FIRE = 8

# Colors
RED = (227, 38, 54)
BLUE = (56, 176, 222)
BLACK = (0, 0, 0)

# Character constants
STEPS_PER_SQUARE = 2
INITIAL_SPEED = 2.333  # Nome: Speed is in squares per second.
SPEED_INCREMENT = 0.666
MAX_SPEED = 9
INITIAL_FIRE = 2
FIRE_INCREMENT = 1
